"""Database test

Revision ID: 7a09180f2ae8
Revises: 
Create Date: 2024-08-03 09:53:21.323076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a09180f2ae8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results_two',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_product_id', sa.String(length=15), nullable=True),
    sa.Column('exchange_product_name', sa.String(length=256), nullable=True),
    sa.Column('oil_id', sa.String(length=4), nullable=True),
    sa.Column('delivery_basis_id', sa.String(length=4), nullable=True),
    sa.Column('delivery_basis_name', sa.String(length=256), nullable=True),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex_trading_results_two')
    # ### end Alembic commands ###
