name: Python app
on: [push,]
jobs:
    build:
          runs-on: ubuntu-latest
    steps:
        -name: checkout code
         user: action/checkout@v3
        
        -name: set up Python
         user: action/setup-python@v4

        with:
            python-version: '3.9'
            -name: Install dependencies
             run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            -name: Run tests
             run: |
                pytest
